DemandMetalFab/Models/TimeMachineParts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DemandMetalFab.Models
{
    public class TimeMachineParts
    {
        public TimeMachineParts()
        {
            this.partes = new MF_Part();

        }
        public MF_Part partes { set; get; }
        public string opmaquina { set; get; }
    }
}

DemandMetalFab/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemandMetalFab.Models;
using ExcelDataReader;

namespace DemandMetalFab.Controllers
{
    public class PartsController : Controller
    {
        List<int> id_maquina = new List<int>();
        List<int> id_maquinahoja1 = new List<int>();
        List<string> num_parthoja1 = new List<string>();
        int columnahoja1 = 1, columnahoja2 = 1;
        private DemandDBEntities db = new DemandDBEntities();

        // GET: Parts
        public ActionResult Index()
        {
            var part = db.MF_Part.Include(p => p.MF_Machine).Include(p => p.MF_Project);
            return View(part.ToList());
        }

        // GET: Parts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MF_Part part = db.MF_Part.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // GET: Parts/Create
        public ActionResult Create()
        {
            ViewBag.Id_Machine = new SelectList(db.MF_Machine, "Id_Machine", "Machine");
            ViewBag.Id_Project = new SelectList(db.MF_Project, "Id_Project", "Project");
            return View();
        }

        // POST: Parts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Part,Num_Part,Id_Project,Id_Machine")] MF_Part part)
        {
            if (ModelState.IsValid)
            {
                db.MF_Part.Add(part);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Machine = new SelectList(db.MF_Machine, "Id_Machine", "Machine", part.Id_Machine);
            ViewBag.Id_Project = new SelectList(db.MF_Project, "Id_Project", "Project", part.Id_Project);
            return View(part);
        }

        // GET: Parts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MF_Part part = db.MF_Part.Find(id);
            List<MF_OpMachine> op = new List<MF_OpMachine>();
            op = db.MF_OpMachine.Where(x => x.Id_Part == id).ToList();    
                

            if (part == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_machine = new SelectList(op, "Machine.Id_Machine", "Machine.Machine", part.Id_Machine);
            ViewBag.Id_Machines = new SelectList(db.MF_Machine, "Id_Machine", "Machine", part.Id_Machine);
            ViewBag.Id_Project = new SelectList(db.MF_Project, "Id_Project", "Project", part.Id_Project);
            return View(part);
        }

        // POST: Parts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Part,Num_Part,Id_Project,Id_Machine")] MF_Part part)
        {
            if (ModelState.IsValid)
            {
                db.Entry(part).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Machine = new SelectList(db.MF_Machine, "Id_Machine", "Machine", part.Id_Machine);
            ViewBag.Id_Project = new SelectList(db.MF_Project, "Id_Project", "Projec1", part.Id_Project);
            return View(part);
        }

        // GET: Parts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MF_Part part = db.MF_Part.Find(id);
            if (part == null)
            {
                return HttpNotFound();
            }
            return View(part);
        }

        // POST: Parts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MF_Part part = db.MF_Part.Find(id);
            db.MF_Part.Remove(part);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Asignacion()
        {
            return View();
        }
        public PartialViewResult FiltroAsignacionParcial()
        {
            return PartialView();
        }
        public PartialViewResult GridAsignacionParcial(string maquinas)
        {
            List<MF_Part> Asignacion_maquinas = new List<MF_Part>();
            try
            {
                List<Int32> Ids_maquinas = new List<int>();

                if (!String.IsNullOrEmpty(maquinas))
                    Ids_maquinas = maquinas.Split(',').ToList().Select(Int32.Parse).ToList();
                else
                    Ids_maquinas = db.MF_Machine.Select(x => x.Id_Machine).ToList();
                //Obtenemos el filtro de los datos seleccionados y mostramos

                Asignacion_maquinas = db.MF_Part
                    .Where(x =>Ids_maquinas.Contains(x.MF_Machine.Id_Machine) && x.Id_Proceso==Datos.proceso).Distinct().ToList();



            }
            catch (Exception e)
            {

            }

            return PartialView(Asignacion_maquinas);
        }
        [HttpPost]
        public JsonResult agregar(int idparte, string idmaquina)
        {
            List<int> id_maquina = idmaquina.Split(',').ToList().Select(Int32.Parse).ToList();
            
            List<MF_OpMachine> opcion= id_maquina.Select(x=>new MF_OpMachine() {Id_Part= x, Id_Machine=x }).ToList();
            db.MF_OpMachine.AddRange(opcion);
            return Json(new { },JsonRequestBehavior.DenyGet);
        }

        public PartialViewResult DropdownMachineParcial()
        {

            return PartialView();
        }

        public JsonResult Actualizarpartes(string Idparte, string Idmaquina)
        {
            MF_Part partes = db.MF_Part.Find(Int32.Parse(Idparte));
            partes.Id_Machine = Int32.Parse(Idmaquina);
            db.SaveChanges();
            return Json(new { actualizar = true }, JsonRequestBehavior.DenyGet);
           
        }
        public JsonResult AddeleOpmachine(string Idparte, string Idmaquina, int opc)
        {
            int idp, idm;
            MF_OpMachine OpMaquina;
            idp = Int32.Parse(Idparte);
            idm = Int32.Parse(Idmaquina);
            switch (opc)
            {
                case 1:
                    OpMaquina = new MF_OpMachine()
                    {
                        Id_Part = idp,
                        Id_Machine = idm
                    };
                    db.MF_OpMachine.Add(OpMaquina);
                    db.SaveChanges();
                    break;
                case 2:
                    OpMaquina = db.MF_OpMachine.Where(x => x.Id_Part == idp && x.Id_Machine == idm).First();
                    db.MF_OpMachine.Remove(OpMaquina);
                    db.SaveChanges();
                    break;
            }
            return Json(new { actualizar = true }, JsonRequestBehavior.DenyGet);
        }


        //vistas time machine
        [HttpPost]
        public JsonResult guardarDatos(string campo, string valoractual, string tipo, int id)
        {
            MF_Part timemachine = db.MF_Part.Find(id);
            decimal valordecimal = 0;
            int valorint = 0;
            switch (tipo)
            {
                case "decimal":
                    valordecimal = Decimal.Parse(valoractual);
                    break;
                case "int":
                    valorint = Int32.Parse(valoractual);
                    break;

            }
            switch (campo)
            {

                case "Setup":
                    timemachine.Set_Up = valordecimal;
                    break;
                case "Cycle":
                    timemachine.Cycle = valordecimal;
                    break;
                case "Qty":
                    timemachine.Quantity = valorint;
                    break;
            }
            db.SaveChanges();
            return Json(new { actualizar = true }, JsonRequestBehavior.DenyGet);
        }
        [HttpPost]
        public JsonResult guardarmaquina(int idparte, int idmaquina)
        {
            try
            {
                MF_Part partes = db.MF_Part.Find(idparte);
                partes.Id_Machine = idmaquina;
                db.SaveChanges();
                return Json(new { actualizar = true }, JsonRequestBehavior.DenyGet);
            }
            catch (Exception)
            {

                return Json(new { actualizar = false }, JsonRequestBehavior.DenyGet);
            }
        }
        public ActionResult TimeMachinePart()
        {
            
            //  try
            //  {
            //      TempData["UserMessage"] = new AlertValidation() { CssClassName = "alert-success", Title = "Success!", Message = "Operation Done." };
            //  //    return RedirectToAction("Success");
            //  }
            //  catch (Exception e)
            //  {

DemandMetalFab/Views/Parts/AddExcelPartial.cshtml
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add part with Excel</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="file" id="fileToUpload" class="form-control" /> <br />
                @*<button id="upload" class="btn btn-primary">Upload</button>*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" id="upload" class="btn btn-primary">Upload</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">


    $(document).ready(function () {
        $("#exampleModal").modal("show");

       $("#upload").click(function () {

    if (window.FormData == undefined)
        alert("Error: FormData is undefined");

    else {
        var fileUpload = $("#fileToUpload").get(0);
        var files = fileUpload.files;

        var fileData = new FormData();

        fileData.append(files[0].name, files[0]);

        $.ajax({
            url: '@Url.Action("Cargar", "Parts")',
            type: 'post',
            datatype: 'json',
            contentType: false,
            processData: false,
            async: false,
            data: fileData,
            success: function (response) {
                alert(response.Message);
                window.location.href = '@Url.Action("TimeMachinePart","Parts")';
            }
        });



    }

});
    });


</script>

DemandMetalFab/Views/Parts/AddTime.cshtml
@*@model DemandMetalFab.Models.Part*@
@model DemandMetalFab.Models.MF_Part

<link href="~/Content/select2/css/select2.min.css" rel="stylesheet" />
<script src="~/Content/select2/js/select2.min.js"></script>

<div class="modal fade bd-example-modal-lg" id="modaladd" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add new part</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-horizontal">

                    <div class="form-group">
                        <label class="control-label col-md-10">Enter the part number</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Num_Part, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Num_Part, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Select the customer</label>
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Customer", null, "Selecciona el Proyecto", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MF_Project.MF_Demand.Id_Customer, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col form-group">
                            <div id="showproject"></div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Assign the machines that develop the part</label>
                            <div class="col-md-10">
                                <select id="Id_machines" class="js-example-responsive" multiple="multiple" style="width: 100%">
                                    @foreach (var item in DemandMetalFab.GlobalCode.Settings.db.MF_Machine.ToList())
                                    {
                                        <option value="@item.Id_Machine">@item.Machine</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col form-group">
                            <div id="showmachine"></div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Set up Time (Hr)</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Set_Up, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Set_Up, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col form-group">
                            <label class="control-label col-md-10">Cycle Time (Hr)</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Cycle, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Cycle, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Quantity</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col form-group">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" onclick="agregarparte()">Add part</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


    $(document).ready(function () {
        $("#modaladd").modal("show");
        $("#Id_Customer").change(function () {
            $('#showproject').load("@Url.Action("DemandshowPartial","Parts")?id=" + $("#Id_Customer").val());
        });
        $("#Id_machines").change(function () {
            $('#showmachine').load("@Url.Action("MachineshowPartial","Parts")?id=" + $("#Id_machines").val());
        });
    });

        function agregarparte() {
            if (validaciones()) {
                //if (ban) {
                $.ajax({
                    url: '@Url.Action("AgregarParte", "Parts")',
                    data: addDates(),
                    type: 'POST',
                    success: function (response) {
                            if (response.Success) {
                               bootoast.toast({
                                  message: response.Message,
                                  type: 'success',
                                  position: 'bottom-center',
                                  timeout: null
                               });
                                window.setTimeout(function () {
                                    window.location.href = '@Url.Action("TimeMachinePart","Parts")';
                                }, 3000)
                                
                            } else {
                                bootoast.toast({
                                  message: response.Message,
                                  type: 'danger',
                                  position: 'bottom-center',
                                  timeout: null
                                });
                            }


                    },
                    error: function () {
                        alert('Error');
                    }
                });
            }
        }

        function addDates() {
            var procesoData = {
                'partes': {
                Num_Part: $('#Num_Part').val(),
                Id_Project: $('#Id_Project').val(),
                Id_Machine: $('#Id_Machine').val(),
                Set_Up:$('#Set_Up').val(),
                Cycle:$('#Cycle').val(),
                Quantity:$('#Quantity').val()
                },
                'opmaquina':new String($('#Id_machines').val())
            };
            return procesoData;
        }

        $(".js-example-responsive").select2({
        width: 'resolve' // need to override the changed default
        });

</script>

DemandMetalFab/Views/Parts/Asignacion.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Machine Assignment</h2>
<br />
<div class="row" id="filtroasignacion"></div>
<div id="gridasignacion"></div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#filtroasignacion').html('<img src="@Url.Content("~/Imagenes/Cargador/loader4.gif")"/>');
        $('#filtroasignacion').load('@Url.Action("FiltroAsignacionParcial","Parts")');
        fnPintarTablaAsign()
    });
     function fnPintarTablaAsign() {
         var Maquinas_seleccionadas = [];

        $.each($('.maquinas_asig'), function (i, item) {
            if ($(item).is(':checked'))
                Maquinas_seleccionadas.push($(item).val());
        });
        var datos= {
            maquinas: Maquinas_seleccionadas.length > 0 ? Maquinas_seleccionadas.join(',') : null
        };
        $("#gridasignacion").empty();
        $('#gridasignacion').html('<img src="@Url.Content("~/Imagenes/Cargador/loader4.gif")"/>');
        $('#gridasignacion').load('@Url.Action("GridAsignacionParcial","Parts")', datos, function () {

         });

    }

</script>

DemandMetalFab/Views/Parts/Details.cshtml
@model DemandMetalFab.Models.MF_Part

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Part</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Num_Part)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Num_Part)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MF_Machine.Machine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MF_Machine.Machine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MF_Project.Project)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MF_Project.Project)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Part }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DemandMetalFab/Views/Parts/EditMachinePartial.cshtml
@model DemandMetalFab.Models.MF_Part

<script src="~/Content/ui-ecommerce/js/jquery-2.0.0.min.js"></script>
<script src="~/Content/ui-ecommerce/js/bootstrap.bundle.min.js"></script>
<link href="~/Content/ui-ecommerce/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/ui-ecommerce/fonts/fontawesome/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="~/Content/select2/css/select2.min.css" rel="stylesheet" />
<script src="~/Content/select2/js/select2.min.js"></script>

<div class="modal fade bd-example-modal-lg" id="modaladd" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit part</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-horizontal">

                    <div class="form-group">
                        <label class="control-label col-md-10">Enter the part number</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Num_Part, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Num_Part, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Select the customer</label>
                            <div class="col-md-10">
                                @Html.DropDownList("Id_Customer", null, "Selecciona el Proyecto", htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MF_Project.MF_Demand.Id_Customer, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col form-group">
                            <div id="showproject"></div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Assign the machines that develop the part</label>
                            <div class="col-md-10">
                                <select id="Id_machines" class="js-example-responsive" multiple="multiple" style="width: 100%">
                                    @foreach (var item in DemandMetalFab.GlobalCode.Settings.db.MF_Machine.ToList())
                                    {
                                        if (DemandMetalFab.GlobalCode.Settings.db.MF_OpMachine.Any(x => x.Id_Part == Model.Id_Part && x.Id_Machine == item.Id_Machine))
                                        {
                                            <option value="@item.Id_Machine" selected>@item.Machine</option>
                                        }
                                        else
                                        {
                                            <option value="@item.Id_Machine">@item.Machine</option>
                                        }

                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col form-group">
                            <div id="showmachine"></div>
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Set up Time (Hr)</label>
                            <div class="col-md-10">
                                <input type="text" id="Set_Up" class="form-control" value="@Model.Set_Up" />
                                @*@Html.EditorFor(model => model.Set_Up, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Set_Up, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        <div class="col form-group">
                            <label class="control-label col-md-10">Cycle Time (Hr)</label>
                            <div class="col-md-10">
                                <input type="text" id="Cycle" class="form-control" value="@Model.Cycle" />
                                @*@Html.EditorFor(model => model.Cycle, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Cycle, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col form-group">
                            <label class="control-label col-md-10">Quantity</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col form-group">
                        </div>
                    </div>

                    @*<div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Agregar Parte" class="btn btn-primary" />
                            </div>
                        </div>
                        </div>*@


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" onclick="EditarParte()">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

        $(document).ready(function () {
            $("#modaladd").modal("show");
            var datos = {
                id: $("#Id_Customer").val(),
                idparte: '@(Html.Raw(Model.Id_Part))'
            };
            var datosmaquina = {
                id: $("#Id_machines").val(),
                idparte:'@(Html.Raw(Model.Id_Part))'
            }
            $('#showproject').load("@Url.Action("DemandshowPartial","Parts")", datos, function () {
            });
            $('#showmachine').load("@Url.Action("MachineshowPartial","Parts")", datosmaquina, function () {
            });

            //cuando seleccionas el cliente
            $("#Id_Customer").change(function () {
                $('#showproject').load("@Url.Action("DemandshowPartial","Parts")?id=" + $("#Id_Customer").val());
            });

            //cuando seleccionas las maquinas
            $("#Id_machines").change(function () {
                $('#showmachine').load("@Url.Action("MachineshowPartial","Parts")?id=" + $("#Id_machines").val());
            });
        });

    function EditarParte() {
        if (validaciones()) {
            //if (ban) {
            $.ajax({
                url: '@Url.Action("EditarParte", "Parts")',
                data: EditDates(),
                type: 'POST',
                success: function (response) {
                        if (response.Success) {
                           bootoast.toast({
                              message: response.Message,
                              type: 'success',
                              position: 'bottom-center',
                              timeout: null
                           });
                            window.setTimeout(function () {
                                window.location.href = '@Url.Action("TimeMachinePart","Parts")';
                            }, 3000)
                            
                        } else {
                            bootoast.toast({
                              message: response.Message,
                              type: 'danger',
                              position: 'bottom-center',
                              timeout: null
                            });
                        }
                },
                error: function () {
                    alert('Error');
                }
            });
        }
        //}
        //ban = true;
         }

        function EditDates() {
            var procesoData = {
                'partes': {
                Id_Part:'@(Html.Raw(Model.Id_Part))',
                Num_Part: $('#Num_Part').val(),
                Id_Project: $('#Id_Project').val(),
                Id_Machine: $('#Id_Machine').val(),
                Set_Up:$('#Set_Up').val(),
                Cycle:$('#Cycle').val(),
                Quantity:$('#Quantity').val()
                },
                'opmaquina':new String($('#Id_machines').val())
            };
            return procesoData;
    }

        $(".js-example-responsive").select2({
        width: 'resolve' // need to override the changed default
        });

</script>