DemandMetalFab/Controllers/DemandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemandMetalFab.Models;
using Newtonsoft.Json;

namespace DemandMetalFab.Controllers
{
    public class DemandsController : Controller
    {
        
        private DemandDBEntities db = new DemandDBEntities();

        // GET: Demands
        public ActionResult Index()
        {
            var demand = db.MF_Demand.Include(d => d.MF_Customer);
            return View(demand.ToList());
        }

        // GET: Demands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MF_Demand demand = db.MF_Demand.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        // GET: Demands/Create
        public ActionResult Create()
        {
            ViewBag.Id_Customer = new SelectList(db.MF_Customer, "Id_Customer", "Customer");
            return View();
        }

        // POST: Demands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Demand,Demand,Id_Customer")] MF_Demand demand)
        {
            if (ModelState.IsValid)
            {
                db.MF_Demand.Add(demand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Customer = new SelectList(db.MF_Customer, "Id_Customer", "Customer", demand.Id_Customer);
            return View(demand);
        }

        // GET: Demands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MF_Demand demand = db.MF_Demand.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Customer = new SelectList(db.MF_Customer, "Id_Customer", "Customer", demand.Id_Customer);
            return View(demand);
        }

        // POST: Demands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Demand,Demand,Id_Customer")] MF_Demand demand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(demand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Customer = new SelectList(db.MF_Customer, "Id_Customer", "Customer", demand.Id_Customer);
            return View(demand);
        }

        // GET: Demands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MF_Demand demand = db.MF_Demand.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        // POST: Demands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MF_Demand demand = db.MF_Demand.Find(id);
            db.MF_Demand.Remove(demand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public PartialViewResult addemandPartial()
        {
            ViewBag.Id_Customer = new SelectList(db.MF_Customer, "Id_Customer", "Customer");
            ViewBag.Id_Sector = new SelectList(db.MF_Sector, "Id_Sector", "Sector");
            return PartialView();
        }
        [HttpPost]
        public JsonResult agregardemanda(string demand, int customer, int sector)
        {
            int item;
            try
            {
                item = (int)db.MF_Demand.OrderByDescending(x => x.Id_Demand).First().Item + 1;
                MF_Demand dem = new MF_Demand()
                {
                    Item=item,
                    Demand = demand,
                    Id_Customer = customer,
                    Id_Sector = sector
                };
                db.MF_Demand.Add(dem);
                db.SaveChanges();
                return Json(new { Success = true, Message = "The demand was successfully added" }, JsonRequestBehavior.DenyGet);
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Message = "The demand could not be added" }, JsonRequestBehavior.DenyGet);
            }
        }
        public PartialViewResult editdemandPartial(int id)
        {
            MF_Demand dem = db.MF_Demand.Find(id);
            ViewBag.Id_Customer = new SelectList(db.MF_Customer, "Id_Customer", "Customer",dem.Id_Customer);
            ViewBag.Id_Sector = new SelectList(db.MF_Sector, "Id_Sector", "Sector",dem.Id_Sector);
            return PartialView(dem);
        }
        [HttpPost]
        public JsonResult editardemanda(int id, string demand, int customer, int sector)
        {
            try
            {
                MF_Demand dem = db.MF_Demand.Find(id);
                dem.Demand = demand;
                dem.Id_Customer = customer;
                dem.Id_Sector = sector;
                
                db.SaveChanges();
                return Json(new { Success = true, Message = "Demand successfully modified" }, JsonRequestBehavior.DenyGet);
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Message = "Error modifying the demand" }, JsonRequestBehavior.DenyGet);
            }
        }
        
        public PartialViewResult deletedemandPartial(int id)
        {
            MF_Demand dem = db.MF_Demand.Find(id);
            return PartialView(dem);
        }
        [HttpPost]
        public JsonResult eliminardemand(int id)
        {
            try
            {
                MF_Demand dem = db.MF_Demand.Find(id);
                db.MF_Demand.Remove(dem);
                db.SaveChanges();
                return Json(new { Success = true, Message = "The demand was successfully removed" }, JsonRequestBehavior.DenyGet);
            }
            catch (Exception)
            {
                return Json(new { Success = true, Message = "Error deleting demand" }, JsonRequestBehavior.DenyGet);
            }
        }

    }
}

DemandMetalFab/Views/Demands/Create.cshtml
@model DemandMetalFab.Models.MF_Demand

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Demand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Demand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Demand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Demand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Customer, "Id_Customer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Customer", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Customer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemandMetalFab/Views/Demands/Delete.cshtml
@model DemandMetalFab.Models.MF_Demand

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Demand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Demand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Demand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemandMetalFab/Views/Demands/Details.cshtml
@model DemandMetalFab.Models.MF_Demand

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Demand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Demand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Demand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MF_Customer.Customer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MF_Customer.Customer)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Demand }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DemandMetalFab/Views/Demands/Edit.cshtml
@model DemandMetalFab.Models.MF_Demand

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Demand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Demand)

        <div class="form-group">
            @Html.LabelFor(model => model.Demand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Demand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Demand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Customer, "Id_Customer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Customer", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Customer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemandMetalFab/Views/Demands/Grafica_MaquinaPartial.cshtml
@model DemandMetalFab.Models.GraficaMensualModel

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.0/Chart.bundle.min.js"></script>
<canvas id="myChart"></canvas>



<script>
    var maquinas = '@(Html.Raw(Model.MaquinasJson))';
    var porcentaje = '@(Html.Raw(Model.PorcentajeJson))';
    var arc = '@(Html.Raw(Model.Percent_Arc))';
    var top_arc = '@(Html.Raw(Model.Percent_Top_arc))';
    var top_box= '@(Html.Raw(Model.Percent_Top_box))';
    var mars_slant = '@(Html.Raw(Model.Percent_Mars_slant))';
    var helix= '@(Html.Raw(Model.Percent_Helix))';
    var helix_xt = '@(Html.Raw(Model.Percent_Helix_xt))';
    var stepper= '@(Html.Raw(Model.Percent_Stepper))';
    var flame = '@(Html.Raw(Model.Percent_Flame))';
    var edge = '@(Html.Raw(Model.Percent_Edge))';
    var in_touch = '@(Html.Raw(Model.Percent_In_touch))';
    var go_bed = '@(Html.Raw(Model.Percent_Go_bed))';
    var cub= '@(Html.Raw(Model.Percent_Cub))';
    var accesorios = '@(Html.Raw(Model.Percent_Accesorios))';
    var invacare = '@(Html.Raw(Model.Percent_Invacare))';
    var propad= '@(Html.Raw(Model.Percent_Propad))';
    var config = {
  type: 'bar',
  data: {
    labels: JSON.parse(maquinas),
    datasets: [{
      type: 'line',
      label: 'LIMITE',
      data: [100,100,100,100,100,100,100,100,100],
      borderColor: 'red',
      fill: false
    }, {
      type: 'bar',
      label: 'ARC',
            backgroundColor: "red",
            data: JSON.parse(arc),
        }, {
      type: 'bar',
      label: 'TOP ARC',
            backgroundColor: "blue",
            data: JSON.parse(top_arc),
        }, {
      type: 'bar',
      label: 'TOP BOX',
            backgroundColor: "purple",
            data: JSON.parse(top_box),
        }, {
      type: 'bar',
      label: 'MARS SLANT',
            backgroundColor: "yellow",
            data: JSON.parse(mars_slant),
        }, {
      type: 'bar',
      label: 'HELIX',
            backgroundColor: "green",
            data: JSON.parse(helix),
        }, {
      type: 'bar',
      label: 'HELIX XT',
            backgroundColor: "brown",
            data: JSON.parse(helix_xt),
        }, {
      type: 'bar',
      label: 'STEPPER',
            backgroundColor: "pink",
            data: JSON.parse(stepper),
        }, {
      type: 'bar',
      label: 'FLAME',
            backgroundColor: "aqua",
            data: JSON.parse(flame),
        }, {
      type: 'bar',
      label: 'EDGE',
            backgroundColor: "orange",
            data: JSON.parse(edge),
        }, {
      type: 'bar',
      label: 'IN TOUCH',
            backgroundColor: "fuchsia",
            data: JSON.parse(in_touch),
        }, {
      type: 'bar',
      label: 'GO BED',
            backgroundColor: "navy",
            data: JSON.parse(go_bed),
        }, {
      type: 'bar',
      label: 'CUB',
            backgroundColor: "lime",
            data: JSON.parse(cub),
        }, {
      type: 'bar',
      label: 'ACCESORIOS',
            backgroundColor: "gray",
            data: JSON.parse(accesorios),
        }, {
      type: 'bar',
      label: 'INVACARE',
            backgroundColor: "teal",
            data: JSON.parse(invacare),
        }, {
      type: 'bar',
      label: 'PROPAD',
            backgroundColor: "silver",
            data: JSON.parse(propad),
        }

    ]
  },
  options: {
    scales: {
      xAxes: [{
        stacked: true
      }],
      yAxes: [{
        stacked: true
      }]
    }
  }
};

var ctx = document.getElementById("myChart").getContext("2d");
new Chart(ctx, config);
</script>

DemandMetalFab/Views/Demands/Index.cshtml
@model IEnumerable<DemandMetalFab.Models.MF_Demand>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Demand of Project</h2>
@if (DemandMetalFab.GlobalCode.Settings.LoggedUser!=null)
{
    <input type="button" class="btn btn-primary" onclick="agregardemand()" value="Add new demand" />
    <br />
    <br />
}
    <table class="table dt">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Demand)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MF_Customer.Customer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MF_Sector.Sector)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Item)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Demand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MF_Customer.Customer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MF_Sector.Sector)
                    </td>
                    <td>
                        @if (DemandMetalFab.GlobalCode.Settings.LoggedUser!=null)
                        {
                            <div class="input-group w-100">
                                <div class="text-right">
                                    <button data-original-title="Edit @item.Demand" type="submit" onclick="editar(@item.Id_Demand)" class="btn btn-outline-success" data-toggle="tooltip">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </div>
                                <br />
                                <br />
                                <div class="text-right">
                                    <button data-original-title="Delete @item.Demand" onclick="eliminar(@item.Id_Demand)" type="submit" class="btn btn-outline-danger" data-toggle="tooltip">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        }
                        </td>
                </tr>
            }
        </tbody>

    </table>

    <div id="modaldema"></div>


    <script type="text/javascript">
    $(document).ready(function () {

    });

    function agregardemand() {
        $("#modaldema").empty();
        $("#modaldema").load("@Url.Action("addemandPartial","Demands")", {}, function () {

        });
    }
    function editar(id) {
        $("#modaldema").empty();
        $("#modaldema").load("@Url.Action("editdemandPartial","Demands")?id="+id);
    }
    function eliminar(id) {
        $("#modaldema").empty();
        $("#modaldema").load("@Url.Action("deletedemandPartial","Demands")?id="+id);
    }

    </script>

DemandMetalFab/Views/Demands/addemandPartial.cshtml
@model DemandMetalFab.Models.MF_Demand
<script src="~/Content/ui-ecommerce/js/jquery-2.0.0.min.js"></script>
<script src="~/Content/ui-ecommerce/js/bootstrap.bundle.min.js"></script>
<link href="~/Content/ui-ecommerce/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/ui-ecommerce/fonts/fontawesome/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

<div class="modal fade" id="modaladdd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add new project</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label col-md-10">Enter the name of demand</label>
                   <div class="col-md-10">
                        @Html.EditorFor(model => model.Demand, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Demand, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-10">Select the customer</label>
                   <div class="col-md-10">
                        @Html.DropDownList("Id_Customer", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Id_Customer, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-10">Select the sector</label>
                    <div class="col-md-10">
                        @Html.DropDownList("Id_Sector", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Id_Sector, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="agregardema()">Add demand</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#modaladdd").modal("show");

    });
    function agregardema() {
        if (validarEmpity($('#Demand').val())) {
            $.ajax({
                url: '@Url.Action("agregardemanda", "Demands")',
                data: { demand: $('#Demand').val(), customer: $('#Id_Customer').val(),sector: $('#Id_Sector').val()},
                type: 'POST',
                success: function (response) {
                      if (response.Success) {
                               bootoast.toast({
                                  message: response.Message,
                                  type: 'success',
                                  position: 'bottom-center',
                                  timeout: null
                               });
                                window.setTimeout(function () {
                                window.location.href = '@Url.Action("Index","Demands")';
                                }, 3000)
                                
                            } else {
                                bootoast.toast({
                                  message: response.Message,
                                  type: 'danger',
                                  position: 'bottom-center',
                                  timeout: null
                                });
                            }
                   
                },
                error: function () {
                    alert('Error');
                }
            });
        }
    }
</script>

DemandMetalFab/Views/Demands/deletedemandPartial.cshtml
@model DemandMetalFab.Models.MF_Demand
<script src="~/Content/ui-ecommerce/js/jquery-2.0.0.min.js"></script>
<script src="~/Content/ui-ecommerce/js/bootstrap.bundle.min.js"></script>
<link href="~/Content/ui-ecommerce/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/ui-ecommerce/fonts/fontawesome/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

<div class="modal fade" id="modaldelet" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete demand</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>¿Do you want to delete @Model.Demand Demand? </h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" onclick="eliminar(@Model.Id_Demand)">Delete</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#modaldelet").modal("show");

    });
    function eliminar(id) {
        $.ajax({
            url: '@Url.Action("eliminardemand", "Demands")',
            data: { id: id },
            type: 'POST',
            success: function (response) {
                if (response.Success) {
                               bootoast.toast({
                                  message: response.Message,
                                  type: 'success',
                                  position: 'bottom-center',
                                  timeout: null
                               });
                                window.setTimeout(function () {
                                window.location.href = '@Url.Action("Index","Demands")';
                                }, 3000)
                                
                            } else {
                                bootoast.toast({
                                  message: response.Message,
                                  type: 'danger',
                                  position: 'bottom-center',
                                  timeout: null
                                });
                            }
            },
            error: function () {
                alert('Error');
            }
        });
        }
</script>

DemandMetalFab/Views/Demands/editdemandPartial.cshtml
@model DemandMetalFab.Models.MF_Demand
<script src="~/Content/ui-ecommerce/js/jquery-2.0.0.min.js"></script>
<script src="~/Content/ui-ecommerce/js/bootstrap.bundle.min.js"></script>
<link href="~/Content/ui-ecommerce/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/ui-ecommerce/fonts/fontawesome/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

<div class="modal fade" id="modaladdd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit demand</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label col-md-10">Enter the name of demand</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Demand, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Demand, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-10">Select the customer</label>
                    <div class="col-md-10">
                        @Html.DropDownList("Id_Customer", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Id_Customer, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-10">Select the sector</label>
                    <div class="col-md-10">
                        @Html.DropDownList("Id_Sector", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Id_Sector, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="editardema()">Save</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#modaladdd").modal("show");

    });
    function editardema() {
        if (validarEmpity($('#Demand').val())) {
            $.ajax({
                url: '@Url.Action("editardemanda", "Demands")',
                data: { id:'@(Html.Raw(Model.Id_Demand))',demand: $('#Demand').val(), customer: $('#Id_Customer').val(),sector: $('#Id_Sector').val()},
                type: 'POST',
                success: function (response) {
                    if (response.Success) {
                               bootoast.toast({
                                  message: response.Message,
                                  type: 'success',
                                  position: 'bottom-center',
                                  timeout: null
                               });
                                window.setTimeout(function () {
                                window.location.href = '@Url.Action("Index","Demands")';
                                }, 3000)
                                
                            } else {
                                bootoast.toast({
                                  message: response.Message,
                                  type: 'danger',
                                  position: 'bottom-center',
                                  timeout: null
                                });
                            }
                },
                error: function () {
                    alert('Error');
                }
            });
        }
    }
</script>