DemandMetalFab/Models/Grafica.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DemandMetalFab.Models
{
    public class Grafica
    {

        public int Id_machine { get; set; }
        public string Machine { get; set; }
        public decimal Matto { get; set; }
        public decimal Tiempo_Total { get; set; }
        public decimal Tiempo_Total_MTTO { get; set; }
        public double Disponibilidad { get; set; }
        public decimal Ocupacion_Maquina { get; set; }
        public decimal Total_Ocupacion { get; set; }
    }
    public class GraficaSinApilar
    {
        public string Jsonmaquinas { get; set; }
        public string JsonPorcentajemaquina { get; set; }
    }
    public class PorcentajeDemanda
    {
        public int Item { get; set; }
        public string Machine { get; set; }
        public int Id_Sector { get; set; }
        public int Id_Demand { get; set; }
        public string Demand { get; set; }
        public double Tiempo_Maquina { get; set; }
        public double Porcentaje_Demanda { get; set; }
        public double Porcentaje_Noventa { get; set; }
    }

    public class PorcentajeTresMeses
    {
        public int Id_turno { get; set; }
        public int Id_Proceso { get; set; }
        public int Id_machine { get; set; }
        public string Machine { get; set; }
        public decimal Matto { get; set; }
        public decimal Tiempo_Total { get; set; }
        public decimal Tiempo_Total_MTTO { get; set; }
        public double Disponibilidad { get; set; }
        public decimal Ocupacion_Maquina { get; set; }
        public decimal Total_Ocupacion { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
    }
   
    public class PorcentajeCliente
    {
        public int Item { get; set; }
        public string Machine { get; set; }
        public int Id_Sector { get; set; }
        public int Id_Customer { get; set; }
        public string Customer { get; set; }
        public double Ocupacion_Cliente { get; set; }
        public double Ocupacion_Noventa { get; set; }
    }
   
    public class BusquedaId
    {
        public int Id_Part { get; set; }
    }

    public class PorcentajeProceso
    {
        public int Id_Proceso { get; set; }
        public string Proceso { get; set; }
        public string Machine { get; set; }
        public decimal Total_Ocupacion { get; set; }
        public string DemandMonth { get; set; }
        public int DemandYear { get; set; }
        public double DiaIndustrial { get; set; }
        public double DiaMedical { get; set; }
        public double DiaProve1 { get; set; }
        public double DiaProve2 { get; set; }
        public double TurnoIndustrial { get; set; }
        public double TurnoMedical { get; set; }
        public double TurnoProve1 { get; set; }
        public double TurnoProve2 { get; set; }
        public int m { get; set; }
    }
}

DemandMetalFab/Controllers/DemandDatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemandMetalFab.Models;
using ExcelDataReader;
using Newtonsoft.Json;

namespace DemandMetalFab.Controllers
{
    public class DemandDatesController : Controller
    {
        private DemandDBEntities db = new DemandDBEntities();


        public ActionResult Index()
        {
            var demandDate = db.MF_DemandDate.Include(d => d.MF_Demand).Include(d => d.MF_WorkDate);
            return View(demandDate.ToList());
        }
        public PartialViewResult GridDemandaPartial(string inicio, string fin)
        {
 
            string[] iniciofecha = inicio.Split(' ');
            string[] finalfecha = fin.Split(' ');
            int iniciomes, inicioanio, finmes, finanio;

            iniciomes = Convert.ToInt32(iniciofecha[0]);
            inicioanio = Convert.ToInt32(iniciofecha[1]);
            finmes = Convert.ToInt32(finalfecha[0]);
            finanio = Convert.ToInt32(finalfecha[1]);

            var idini = db.MF_WorkDate.Where(x => x.Id_DemandMonth == iniciomes && x.Id_DemandYear == inicioanio).First();
            var idfin = db.MF_WorkDate.Where(x => x.Id_DemandMonth == finmes && x.Id_DemandYear == finanio).First();

            ViewBag.idini = idini.Id_WorkDate;
            ViewBag.idfin = idfin.Id_WorkDate;
            ViewBag.iniciomes = iniciomes;
            ViewBag.finmes = finmes;
            ViewBag.inicioanio = inicioanio;
            ViewBag.finanio = finanio;

            ViewBag.demandamensual = db.MF_DemandDate.Where(x => x.Id_WorkDate >= idini.Id_WorkDate && x.Id_WorkDate <= idfin.Id_WorkDate).ToList();
            return PartialView();
        }
        public PartialViewResult Grafica_MaquinaPartial(int mes, int anio, int turnoindustrial, double diasindustrial, int turnomedical, double diasmedical, int turnoprovee1, double diasprovee1, int turnoprovee2, double diasprovee2)
        {
            DataChartModel chart = new DataChartModel();
            DataSets datasets = new DataSets();
            DataSetDetail datasetdetails;
            Options option = new Options();
            Scales scales = new Scales();
            Axes xAxes = new Axes() { stacked = true };
            Axes yAxes = new Axes() { stacked = true };

            ActualizarDatos(mes,anio,turnoindustrial,diasindustrial,turnomedical,diasmedical,turnoprovee1,diasprovee1,turnoprovee2,diasprovee2);

            var resultado = db.Database.SqlQuery<PorcentajeDemanda>("EXEC MF_Porcentaje_Demanda {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", Datos.diaindustrial, Datos.diamedical, Datos.diaprove1, Datos.diaprove2, Datos.mes, Datos.anio, Datos.horasindustrial, Datos.horasmedical, Datos.horasprove1, Datos.horasprove2,Datos.proceso).ToList();

            foreach (var item in db.MF_Machine.Where(x=>x.Id_Proceso==Datos.proceso).ToList())
            {
                chart.labels.Add(item.Machine);
                datasets.data.Add(100);
            }

            datasets.type = "line";
            datasets.label = "LIMIT";
            datasets.borderColor = "red";
            datasets.fill = false;

            chart.datasets.Add(datasets);

            foreach (var dem in db.MF_Demand.ToList())
            {
                datasetdetails = new DataSetDetail();
                datasetdetails.type = "bar";
                datasetdetails.label = dem.Demand;
                datasetdetails.backgroundColor = BarColor((int)dem.Item);
                foreach (var res in resultado.Where(x => x.Id_Demand == dem.Id_Demand).OrderBy(x=>x.Item).ToList())
                {
                    if (res.Porcentaje_Noventa == 0)
                    {
                        datasetdetails.data.Add("");
                    }
                    else
                    {
                        datasetdetails.data.Add(res.Porcentaje_Noventa.ToString());
                    }
                }
                chart.datasets.Add(datasetdetails);
            }

            scales.xAxes.Add(xAxes);
            scales.yAxes.Add(yAxes);

            ViewBag.JsonDataSet = JsonConvert.SerializeObject(chart);


            return PartialView();
        }

        public PartialViewResult Ocupacion_maquinasParcial()
        {
            ViewBag.ocupacion = db.Database.SqlQuery<Grafica>("EXEC MF_Porcentaje_Maquina {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", Datos.diaindustrial, Datos.diamedical,Datos.diaprove1,Datos.diaprove2, Datos.mes, Datos.anio, Datos.horasindustrial, Datos.horasmedical,Datos.horasprove1,Datos.horasprove2,Datos.proceso).ToList();
            return PartialView();
        }
        public ActionResult ShowDemand()
        {
            var demandDate = db.MF_DemandDate.Include(d => d.MF_Demand).Include(d => d.MF_WorkDate);
            return View(demandDate.ToList());
        }

        public ActionResult DemandDetalle()
        {
           
            var resultado = db.Database.SqlQuery<PorcentajeDemanda>("EXEC MF_Porcentaje_Demanda {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", Datos.diaindustrial, Datos.diamedical, Datos.diaprove1, Datos.diaprove2, Datos.mes, Datos.anio, Datos.horasindustrial, Datos.horasmedical, Datos.horasprove1, Datos.horasprove2,Datos.proceso).ToList();
            var total = db.Database.SqlQuery<Grafica>("EXEC MF_Porcentaje_Maquina  {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", Datos.diaindustrial, Datos.diamedical, Datos.diaprove1, Datos.diaprove2, Datos.mes, Datos.anio, Datos.horasindustrial, Datos.horasmedical, Datos.horasprove1, Datos.horasprove2,Datos.proceso).ToList();
            ViewBag.valores = resultado;
            ViewBag.ocupacion = total;
            
            return View();
        }

    
        public PartialViewResult GraficanoapiladaPartial(int mes, int anio, int turnoindustrial, double diasindustrial, int turnomedical, double diasmedical,int turnoprovee1,double diasprovee1, int turnoprovee2, double diasprovee2)
        {
            DataChartModel chart = new DataChartModel();
            DataSets datasets = new DataSets();
            DataSetDetail datasetdetails;
            Options option = new Options();
            Scales scales = new Scales();
            Axes xAxes = new Axes() { stacked = true };
            Axes yAxes = new Axes() { stacked = true };
            
            ActualizarDatos(mes, anio, turnoindustrial, diasindustrial, turnomedical, diasmedical,turnoprovee1,diasprovee1,turnoprovee2,diasprovee2);
           
            
            var resultado = db.Database.SqlQuery<Grafica>("EXEC MF_Porcentaje_Maquina {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", Datos.diaindustrial, Datos.diamedical, Datos.diaprove1, Datos.diaprove2, Datos.mes, Datos.anio, Datos.horasindustrial, Datos.horasmedical, Datos.horasprove1, Datos.horasprove2,Datos.proceso).ToList();
            
            foreach (var item in db.MF_Machine.Where(x => x.Id_Proceso == Datos.proceso).ToList())
            {
                chart.labels.Add(item.Machine);
                datasets.data.Add(100);
            }

            datasets.type = "line";
            datasets.label = "LIMIT";
            datasets.borderColor = "red";
            datasets.fill = false;

            chart.datasets.Add(datasets);

            datasetdetails = new DataSetDetail();
            datasetdetails.type = "bar";
            datasetdetails.label = "Machine Percentage";
            datasetdetails.backgroundColor = BarColor(1);
            foreach (var res in resultado.OrderBy(x => x.Id_machine).ToList())
            {
                if (res.Total_Ocupacion == 0)
                {
                    datasetdetails.data.Add("");
                }
                else
                {
                    datasetdetails.data.Add(res.Total_Ocupacion.ToString());
                }
            }
            chart.datasets.Add(datasetdetails);
            scales.xAxes.Add(xAxes);
            scales.yAxes.Add(yAxes);

            ViewBag.JsonDataSet = JsonConvert.SerializeObject(chart);

            return PartialView();
        }
        [HttpPost]
        public JsonResult EditarQty(int id_DemandDate, int qty)
        {
          
            try
            {
                MF_DemandDate Demandat = db.MF_DemandDate.Find(id_DemandDate);
                Demandat.Quantity = qty;
                db.SaveChanges();
                return Json(new { Success = true }, JsonRequestBehavior.DenyGet);
            }
            catch (Exception e)
            {
                return Json(new { Success = false }, JsonRequestBehavior.DenyGet);
            }
        }

        public PartialViewResult addDemand()
        {
            return PartialView();
        }
        public JsonResult agregardemandas(string valores, int mes, int anio, int dias, int semanas)
        {
            int item;
            using (DbContextTransaction dbTran = db.Database.BeginTransaction())
            {
                try
                {
                    MF_WorkDate work = new MF_WorkDate()
                    {
                        Id_DemandMonth = mes,
                        Id_DemandYear = anio,
                        WorkDays = dias,
                        WorkWeeks = semanas
                    };
                    db.MF_WorkDate.Add(work);
                    db.SaveChanges();
                   
                    item = (int)db.MF_DemandDate.OrderByDescending(x => x.Id_DemandDate).First().Item;
                    var id_workdate = db.MF_WorkDate.Where(x => x.Id_DemandMonth == mes && x.Id_DemandYear == anio).First();
                    List<Int32> valor_demanda = new List<int>();
                    valor_demanda = valores.Split(',').ToList().Select(Int32.Parse).ToList();
                    int y = (int)db.MF_Demand.First().Id_Demand;

DemandMetalFab/Views/DemandDates/AddExcelPartial.cshtml
<script src="~/Content/spinner/js/jquery-spinner.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="~/Content/spinner/css/jquery-spinner.min.css" type="text/css">
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update demand month</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="file" id="fileToUpload" class="form-control" /> <br />
                @*<button id="upload" class="btn btn-primary">Upload</button>*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" id="upload" class="btn btn-primary">Upload</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
        var spinner = new jQuerySpinner({
        parentId: 'spinn'
        });


    $(document).ready(function () {
        $("#exampleModal").modal("show");

       $("#upload").click(function () {

    if (window.FormData == undefined)
        alert("Error: FormData is undefined");

    else {
        var fileUpload = $("#fileToUpload").get(0);
        var files = fileUpload.files;

        var fileData = new FormData();

        fileData.append(files[0].name, files[0]);

        $("#exampleModal").modal("hide");
        spinner.show();
        $.ajax({
            url: '@Url.Action("Cargar", "DemandDates")',
            type: 'post',
            datatype: 'json',
            contentType: false,
            processData: false,
            data: fileData,
            success: function (response) {
                spinner.hide();
                if (response.Success) {
                   bootoast.toast({
                      message: response.Message,
                      type: 'success',
                      position: 'bottom-center',
                      timeout: null,
                      animationDuration: 300
                   });
                    window.setTimeout(function () {
                        window.location.href = '@Url.Action("Index","DemandDates")';
                    }, 3000)

                } else {
                    bootoast.toast({
                      message: response.Message,
                      type: 'danger',
                      position: 'bottom-center',
                      timeout: null,
                      animationDuration: 300
                    });
                }
            }
        });



    }

});
    });


</script>

DemandMetalFab/Views/DemandDates/Create.cshtml
@model DemandMetalFab.Models.MF_DemandDate

@{
    ViewBag.Title = "Create";
     Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DemandDate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_Demand, "Id_Demand", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Demand", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Demand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_WorkDate, "Id_WorkDate", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_WorkDate", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_WorkDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemandMetalFab/Views/DemandDates/CustomerGraficaPartial.cshtml
<script src="~/Scripts/chartjs-plugin-datalabels.js"></script>
<script src="~/Scripts/chartjs-plugin-datalabels.min.js"></script>

<h4 class="text-center">Stacked Bar Graph of Capacity by Customer </h4>
<br />
<canvas id="myChart"></canvas>

<div id="modalgrafica"></div>



<script>
   var data= JSON.parse('@(Html.Raw(ViewBag.JsonDataSet))');
    var config = {
  type: 'bar',
  data: data,
  options: {
    scales: {
      xAxes: [{
        stacked: true
      }],
      yAxes: [{
        stacked: true
      }]
    }
  }
};

var ctx = document.getElementById("myChart").getContext("2d");
    new Chart(ctx, config);

   
</script>

DemandMetalFab/Views/DemandDates/DeleteDemandDatesPartial.cshtml
<script src="~/Content/ui-ecommerce/js/jquery-2.0.0.min.js"></script>
<script src="~/Content/ui-ecommerce/js/bootstrap.bundle.min.js"></script>
<link href="~/Content/ui-ecommerce/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/ui-ecommerce/fonts/fontawesome/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

<div class="modal fade" id="modaldele" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete monthly demand</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Select the month and year of the demand to delete</h5>
                <table class="table table-borderless text-center">
                    <tr>
                        <td scope="row">MONTH</td>
                        <td scope="row">
                            @*<select id="m" class="form-control text-center">
                                @foreach (var m in DemandMetalFab.GlobalCode.Settings.db.DemandMonth.ToList())
                                {
                                    <option id="@m.Id_DemandMonth" value="@m.Id_DemandMonth">@m.DemandMonth1</option>
                                }
                            </select>*@
                            <div id="mesdeletedisp"></div>
                        </td>
                        <td scope="row">YEAR</td>
                        <td scope="row">
                            <select id="a" class="form-control text-center" onchange="updatedeletemonth()">
                                    @foreach (var m in DemandMetalFab.GlobalCode.Settings.db.MF_DemandYear.Where(x => DemandMetalFab.GlobalCode.Settings.db.MF_WorkDate.Where(es => es.Id_DemandYear == x.Id_DemandYear).Any()).ToList())
                                    {
                                        <option id="@m.Id_DemandYear" value="@m.Id_DemandYear">@m.DemandYear</option>
                                    }
                            </select>
                        </td>
                        <td><button class="btn btn-primary" onclick="search()">Search</button></td>
                    </tr>
                </table>

                <div id="mostrardatos"></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="deletedemand()">Delete Demand</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#modaldele").modal("show");
        updatedeletemonth();
    });

    function search() {
         var datos = {
                mes: $('#m').val(),
                anio: $('#a').val()
            };
            $("#mostrardatos").empty();
            $("#mostrardatos").html('<img src="@Url.Content("~/Imagenes/Cargador/loader4.gif")"/>');
            $('#mostrardatos').load("@Url.Action("showGridnoeditPartial", "DemandDates")", datos, function () {
            });
    }
    function deletedemand(){
        $.ajax({
                url: '@Url.Action("EliminarDemandaMensual", "DemandDates")',
                data: { mes: $('#m').val(), anio: $('#a').val() },
                type: 'POST',
            success: function (response) {

                if (response.Success) {
                               bootoast.toast({
                                  message: response.Message,
                                  type: 'success',
                                  position: 'bottom-center',
                                  timeout: null
                               });
                                window.setTimeout(function () {
                                      window.location.href = '@Url.Action("Index","DemandDates")';
                                }, 3000)
                                
                            } else {
                                bootoast.toast({
                                  message: response.Message,
                                  type: 'danger',
                                  position: 'bottom-center',
                                  timeout: null
                                });
                            }

                },
                error: function () {
                    alert('Error');
                }
            });
    }
    function updatedeletemonth() {
        var id = $('#a').val();
        $('#mesdeletedisp').empty();
        $('#mesdeletedisp').load("@Url.Action("mesesdeletePartial","DemandDates")?id=" + id);
    }

   

</script>

DemandMetalFab/Views/DemandDates/DemandDetalle.cshtml
@model IEnumerable<DemandMetalFab.Models.PorcentajeDemanda>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    string titulodemand = "";
}
<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th colspan="10" style="background-color:blue;color:white">PERCENTAGE MATRIX OF TIMES</th>
        </tr>
        <tr>
            <th scope="col" style="background-color:blue;color:white">PROJECT</th>
            @foreach (var item in DemandMetalFab.GlobalCode.Settings.db.MF_Machine.Where(x => x.Id_Proceso == Datos.proceso).ToList())
            {
                <th scope="col" style="background-color:cornflowerblue;color:white">@item.Machine</th>
            }

        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row" style="background-color:blue;color:white">LIMIT</th>
            @foreach (var item in DemandMetalFab.GlobalCode.Settings.db.MF_Machine.Where(x => x.Id_Proceso == Datos.proceso).ToList())
            {
                <td>100%</td>
            }
        </tr>

        @foreach (var dem in DemandMetalFab.GlobalCode.Settings.db.MF_Demand.ToList())
        {
            <tr>
                <th scope="row" style="background-color:blue;color:white">@dem.Demand</th>
                @foreach (var item in ((List<DemandMetalFab.Models.PorcentajeDemanda>)ViewBag.valores).Where(x=>x.Id_Demand==dem.Id_Demand).OrderBy(x=>x.Item).ToList())
                {
                        <td>@item.Porcentaje_Demanda%</td>
                    
                }
            </tr>
        }
        @for(int y=1;y<=5;y++)
        {
            if (y == 1) { titulodemand = "T. Matto. HR x dia"; }
            if (y == 2) { titulodemand = "T. TOTAL"; }
            if (y == 3) { titulodemand = "T. TOTAL+ MTTO"; }
            if (y == 4) { titulodemand = "Disponibilidad maq."; }
            if (y == 5) { titulodemand = "Ocupacion maquina"; }
            <tr>
                <th scope="row" style="background-color:blue;color:white">@titulodemand</th>
                @if (y == 1)
                {
                    foreach (var dem in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
                    {
                        <td>@(((double)dem.Matto / dem.Disponibilidad).ToString("0.00"))%</td>
                    }
                }
                @if (y == 2)
                {
                    foreach (var dem in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
                    {
                        <td>@dem.Tiempo_Total.ToString("0.00")%</td>
                    }
                }
                @if (y == 3)
                {
                    foreach (var dem in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
                    {
                        <td>@dem.Tiempo_Total_MTTO.ToString("0.00")%</td>
                    }
                }
                @if (y == 4)
                {
                    foreach (var dem in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
                    {
                        <td>@dem.Disponibilidad%</td>
                    }
                }
                @if (y == 5)
                {
                    foreach (var dem in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
                    {
                     <td>@dem.Ocupacion_Maquina.ToString("0.00")%</td>
                    }
                }
            </tr>
        }
      

    </tbody>
</table>
<br />
<br />
<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th colspan="10" style="background-color:blue;color:white">MACHINE OCCUPATION</th>
        </tr>
        <tr>
            <th scope="col" style="background-color:blue;color:white">EFFICIENCY</th>
            @foreach (var item in DemandMetalFab.GlobalCode.Settings.db.MF_Machine.Where(x => x.Id_Proceso == Datos.proceso).ToList())
            {
                <th scope="col" style="background-color:cornflowerblue;color:white">@item.Machine</th>
            }

        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row" style="background-color:blue;color:white">LIMIT</th>
            @foreach (var item in DemandMetalFab.GlobalCode.Settings.db.MF_Machine.Where(x => x.Id_Proceso == Datos.proceso).ToList())
            {
                <td>100%</td>
            }
        </tr>
        <tr>
            <th scope="row" style="background-color:blue;color:white">90%</th>
            @foreach (var item in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
            {
                if (item.Total_Ocupacion <= 70)
                {
                    <td style="background-color:lawngreen">@item.Total_Ocupacion%</td>
                }
                if (item.Total_Ocupacion > 70 && item.Total_Ocupacion <= 100)
                {
                    <td style="background-color:orange">@item.Total_Ocupacion%</td>
                }
                if (item.Total_Ocupacion > 100)
                {
                    <td style="background-color:red">@item.Total_Ocupacion%</td>
                }
            }
        </tr>
        <tr>
            <th scope="row" style="background-color:blue;color:white">100%</th>
            @foreach (var item in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
            {
                <td>@item.Ocupacion_Maquina.ToString("0.00")%</td>
            }
        </tr>
        <tr>
            <th scope="row" style="background-color:blue;color:white">MAINTENANCE</th>
            @foreach (var item in (List<DemandMetalFab.Models.Grafica>)ViewBag.ocupacion)
            {
                <td>@item.Matto</td>
            }
        </tr>
    </tbody>
</table>

@*<div id="ocupacion_maquina"></div>*@

<script type="text/javascript">
    @*$(document).ready(function () {

            $("#ocupacion_maquina").empty();
            $('#ocupacion_maquina').html('<img src="@Url.Content("~/Imagenes/Cargador/loader4.gif")"/>');
        $('#ocupacion_maquina').load("@Url.Action("Ocupacion_maquinasParcial", "DemandDates")", {}, function () {
            });
    });*@

</script>